// -----------------------------------------------------
// This file is automatically generated - do not change
// original source Unicode UTF-16 file - kpttu16.txt

// ===================================================
//  kpttuc.cpp
//  Kpt style character Unicode codes
//


// -----------------------
#include "stdafx.h"

#include "envir.h"

#if CompilerGr==Msvc
#include <afx.h>
#endif
#include <stdio.h>
#include <string>
#if OsGr==MSWin
#include <windows.h>
#endif

#include "kpstdlib.h"
#include "kptt.h"


// -----------------------
UniChar iaUniChars[C_CharArrSize37] =
{
  C_Nul,     /* 0x00 */
  C_Soh,     /* 0x01 */
  C_Stx,     /* 0x02 */
  C_Etx,     /* 0x03 */
  C_Eot,     /* 0x04 */
  C_Enq,     /* 0x05 */
  C_Ack,     /* 0x06 */
  C_Bel,     /* 0x07 */
  C_Bs,      /* 0x08 */
  C_Ht,      /* 0x09 */
  C_Lf,      /* 0x0a */
  C_Vt,      /* 0x0b */
  C_Ff,      /* 0x0c */
  C_Cr,      /* 0x0d */
  C_So,      /* 0x0e */
  C_Si,      /* 0x0f */
  C_Dle,     /* 0x10 */
  C_Dc1,     /* 0x11 */
  C_Dc2,     /* 0x12 */
  C_Dc3,     /* 0x13 */
  C_Dc4,     /* 0x14 */
  C_Nak,     /* 0x15 */
  C_Syn,     /* 0x16 */
  C_Etb,     /* 0x17 */
  C_Can,     /* 0x18 */
  C_Em,      /* 0x19 */
  C_Sub,     /* 0x1a */
  C_Esc,     /* 0x1b */
  C_Fs,      /* 0x1c */
  C_Gs,      /* 0x1d */
  C_Rs,      /* 0x1e */
  C_Us,      /* 0x1f */

  C_Spc,     /* Space */
  C_Excl,    /* !  Exclamation Mark (s/auktukas) */
  C_Quote,   /* "  Quotation Mark (kabute%s) */
  C_Numb,    /* #  Number Sign (Numerio zenklas) */
  C_Doll,    /* $  Currency Sign (Pinigu zenklas) */
  C_Perc,    /* %  Per Cent Sign (procento z/enklas) */
  C_Amp,     /* &  Ampersand (Ampersandas) */
  C_Apost,   /* '  Apostrophe (Apostrofa, apostrofas, kablelio formos) */
  C_Lpar,    /* (  Left Parenthesis (kairysis skliaustas) */
  C_Rpar,    /* )  Right Parenthesis (des/inysis skliaustas) */
  C_Ast,     /* *  Asterisk (Zvaigzdute) */
  C_Plus,    /* +  Plus Sign (pliusas) */
  C_Comma,   /* ,  Comma (kablelis) */
  C_Dash,    /* -  Dash, Hyphen, Minus Sign (minusas) */
  C_Point,   /* .  Full Stop, Period, Point (tas/kas) */
  C_Slash,   /* /  Slash, Solidus (Istrizas bruksnys) */
  C_0,       /* 0 */
  C_1,       /* 1 */
  C_2,       /* 2 */
  C_3,       /* 3 */
  C_4,       /* 4 */
  C_5,       /* 5 */
  C_6,       /* 6 */
  C_7,       /* 7 */
  C_8,       /* 8 */
  C_9,       /* 9 */
  C_Colon,   /* :  Colon (dvitas/kis) */
  C_Semic,   /* ;  Semi-colon (kabliatas/kis) */
  C_Less,    /* <  Less than Sign (maz/iau) */
  C_Eq,      /* =  Equals Sign (lygybe%s z/enklas) */
  C_Great,   /* >  Greater than Sign (daugiau) */
  C_Quest,   /* ?  Question Mark (klaustukas) */

  C_At,      /* @  Commercial At (Prekybinis zenklas "Pas") */
  C_A,       /* A */
  C_B,       /* B */
  C_C,       /* C */
  C_D,       /* D */
  C_E,       /* E */
  C_F,       /* F */
  C_G,       /* G */
  C_H,       /* H */
  C_I,       /* I */
  C_J,       /* J */
  C_K,       /* K */
  C_L,       /* L */
  C_M,       /* M */
  C_N,       /* N */
  C_O,       /* O */
  C_P,       /* P */
  C_Q,       /* Q */
  C_R,       /* R */
  C_S,       /* S */
  C_T,       /* T */
  C_U,       /* U */
  C_V,       /* V */
  C_W,       /* W */
  C_X,       /* X */
  C_Y,       /* Y */
  C_Z,       /* Z */
  C_Lbrack,  /* [  Left Square Bracket (Kairysis lauztinis skliaustas) */
  C_Lslash,  /* \  Reverse Solidus, Reverse Slash (Atvirkscias istrizas bruksnys) */
  C_Rbrack,  /* ]  Right Square Bracket (Desinysis lauztinis skliaustas) */
  C_Circ,    /* ^  Circumflex Accent (Cirkumfleksas), standalone */
  C_Underl,  /* _  Underline (Pabraukimas) */

  C_Grave,   /* `  Grave Accent (gravis), standalone */
  C_a,       /* a */
  C_b,       /* b */
  C_c,       /* c */
  C_d,       /* d */
  C_e,       /* e */
  C_f,       /* f */
  C_g,       /* g */
  C_h,       /* h */
  C_i,       /* i */
  C_j,       /* j */
  C_k,       /* k */
  C_l,       /* l */
  C_m,       /* m */
  C_n,       /* n */
  C_o,       /* o */
  C_p,       /* p */
  C_q,       /* q */
  C_r,       /* r */
  C_s,       /* s */
  C_t,       /* t */
  C_u,       /* u */
  C_v,       /* v */
  C_w,       /* w */
  C_x,       /* x */
  C_y,       /* y */
  C_z,       /* z */
  C_Lcurl,   /* {  Left Curly Bracket (Kairysis riestinis skliaustas) */
  C_Vertl,   /* |  Vertical Line (Vertikali Linija) */
  C_Rcurl,   /* }  Right Curly Bracket (Desinysis riestinis skliaustas) */
  C_Tilde,   /* ~  Tilde (Overline) (Tilde, Bruksnys virsuje), standalone */

  C_Del,

  0x00C6, // C_AE,
  0x00E6, // C_ae,
  0x0152, // C_OE,
  0x0153, // C_oe,
  0x0132, // C_IJ,
  0x0133, // C_ij,
  0x00DF, // C_ss,      /* sharp s (german, C_beta) */

  0x0410, // C_A_Cyr,
  0x0411, // C_B_Cyr,
  0x0412, // C_V_Cyr,
  0x0413, // C_G_Cyr,
  0x0414, // C_D_Cyr,
  0x0415, // C_E_Cyr,
  0x0416, // C_Zh_Cyr,
  0x0417, // C_Z_Cyr,
  0x0418, // C_I_Cyr,
  0x0419, // C_J_Cyr,
  0x041A, // C_K_Cyr,
  0x041B, // C_L_Cyr,
  0x041C, // C_M_Cyr,
  0x041D, // C_N_Cyr,
  0x041E, // C_O_Cyr,
  0x041F, // C_P_Cyr,
  0x0420, // C_R_Cyr,
  0x0421, // C_S_Cyr,
  0x0422, // C_T_Cyr,
  0x0423, // C_U_Cyr,
  0x0424, // C_F_Cyr,
  0x0425, // C_H_Cyr,
  0x0426, // C_C_Cyr,
  0x0427, // C_Ch_Cyr,
  0x0428, // C_Sh_Cyr,
  0x0429, // C_Shch_Cyr,
  0x042A, // C_Hard_Cyr,
  0x042B, // C_Y_Cyr,
  0x042C, // C_Soft_Cyr,
  0x042D, // C_Ee_Cyr,
  0x042E, // C_Ju_Cyr,
  0x042F, // C_Ja_Cyr,

  0x0430, // C_a_Cyr,
  0x0431, // C_b_Cyr,
  0x0432, // C_v_Cyr,
  0x0433, // C_g_Cyr,
  0x0434, // C_d_Cyr,
  0x0435, // C_e_Cyr,
  0x0436, // C_zh_Cyr,
  0x0437, // C_z_Cyr,
  0x0438, // C_i_Cyr,
  0x0439, // C_j_Cyr,
  0x043A, // C_k_Cyr,
  0x043B, // C_l_Cyr,
  0x043C, // C_m_Cyr,
  0x043D, // C_n_Cyr,
  0x043E, // C_o_Cyr,
  0x043F, // C_p_Cyr,
  0x0440, // C_r_Cyr,
  0x0441, // C_s_Cyr,
  0x0442, // C_t_Cyr,
  0x0443, // C_u_Cyr,
  0x0444, // C_f_Cyr,
  0x0445, // C_h_Cyr,
  0x0446, // C_c_Cyr,
  0x0447, // C_ch_Cyr,
  0x0448, // C_sh_Cyr,
  0x0449, // C_shch_Cyr,
  0x044A, // C_hard_Cyr,
  0x044B, // C_y_Cyr,
  0x044C, // C_soft_Cyr,
  0x044D, // C_ee_Cyr,
  0x044E, // C_ju_Cyr,
  0x044F, // C_ja_Cyr,

/* Additional greek chars variations follow later */
  0x0391, // C_Alpha,
  0x0392, // C_Beta,
  0x0393, // C_Gamma,
  0x0394, // C_Delta,
  0x0395, // C_Epsilon,
  0x0396, // C_Zeta,
  0x0397, // C_Eta,
  0x0398, // C_Theta,
  0x0399, // C_Jota,
  0x039A, // C_Kappa,
  0x039B, // C_Lambda,
  0x039C, // C_My,
  0x039D, // C_Ny,
  0x039E, // C_Xi,
  0x039F, // C_Omicron,
  0x03A0, // C_Pi,
  0x03A1, // C_Rho,
  0x03A3, // C_Sigma,
  0x03A4, // C_Tau,
  0x03A5, // C_Ypsilon,
  0x03A6, // C_Phi,
  0x03A7, // C_Chi,
  0x03A8, // C_Psi,
  0x03A9, // C_Omega,

  0x03B1, // C_alpha,
  0x03B2, // C_beta,
  0x03B3, // C_gamma,
  0x03B4, // C_delta,
  0x03B5, // C_epsilon,  // curly epsilon
  0x03B6, // C_zeta,
  0x03B7, // C_eta,
  0x03B8, // C_theta,    // straight theta
  0x03B9, // C_jota,
  0x03BA, // C_kappa,    // straight kappa
  0x03BB, // C_lambda,
  0x03BC, // C_my,
  0x03BD, // C_ny,
  0x03BE, // C_xi,
  0x03BF, // C_omicron,
  0x03C0, // C_pi,       // straight pi
  0x03C1, // C_rho,      // straight rho
  0x03C3, // C_sigma,    // inner sigma
  0x03C4, // C_tau,
  0x03C5, // C_ypsilon,
  0x03C6, // C_phi,      // straight phi !!! must be like russian C_f_cyr
  0x03C7, // C_chi,
  0x03C8, // C_psi,

  0x03C9, // C_omega,

  0x00F0, // C_delt_Mn, /* delta_Minus (skardi th) */

             /* All accents have no width (over the next letter) */
             /* more accents later - C_...Acc */
  0x0301, // C_Acute,   /* '  Acute (aku/tas, C_Apost, C_AcuteNcomb, des/inysis kirtis) */
  0x030B, // 0x02DD - non combining // C_Dacut,   /* '' Double Acute */
  0x0328, // 0x02DB // C_Ogon,    /* ,  Ogonek (nosine) */
  0x0307, // 0x02D9 // C_Adot,    /* .  Dot Above (. virsuje) */
  0x030C, // 0x02C7 // C_Car,     /* v  Carron, Caron (Pauksciukas) */
  0x0304, // 0x02C9 // C_Macr,    /* _  Macron, Overline (bruksnys virsuje) */
  0x0308, // 0x00A8 // C_Diaer,   /* .. Diaeresis (Umlaut) */
  0x030A, // 0x02DA - non combining // C_Ring,    /* o  Ring (Circle) Above (o virsuje, degree) */
  0x0312, // C_Tacom,   /* '  Turned Comma Above */
  0x0326, // C_Bcomma,  /* ,  Comma Bellow */
  0x0327, // C_Cedil,   /* ,  Cedilla (atbula nosine) */

  0x0104, // C_A_Ogon,  /* A, */
  0x0105, // C_a_Ogon,  /* a, */
  0x0118, // C_E_Ogon,  /* E, */
  0x0119, // C_e_Ogon,  /* e, */
  0x012E, // C_I_Ogon,  /* I, */
  0x012F, // C_i_Ogon,  /* i, */
  0x0172, // C_U_Ogon,  /* U, */
  0x0173, // C_u_Ogon,  /* u, */

  0x0116, // C_E_Adot,  /* E. */
  0x0117, // C_e_Adot,  /* e. */
  0x017B, // C_Z_Adot,  /* Z. */
  0x017C, // C_z_Adot,  /* z. */

  C_Nul, // C_G_Cyr_Adot, /* G Cyr . */
  C_Nul, // C_g_Cyr_Adot, /* g Cyr . */

  0x010C, // C_C_Car,   /* Cv */
  0x010D, // C_c_Car,   /* cv */
  0x010E, // C_D_Car,   /* Dv */
  0x010F, // C_d_Car,   /* dv */  !!!
  0x011A, // C_E_Car,   /* Ev */
  0x011B, // C_e_Car,   /* ev */
  0x013D, // C_L_Car,   /* Lv */  !!!
  0x013E, // C_l_Car,   /* lv */  !!! 
  0x0147, // C_N_Car,   /* Nv */
  0x0148, // C_n_Car,   /* nv */


  0x0158, // C_R_Car,   /* Rv */
  0x0159, // C_r_Car,   /* rv */
  0x0160, // C_S_Car,   /* Sv */
  0x0161, // C_s_Car,   /* sv */
  0x0164, // C_T_Car,   /* Tv */
  0x0165, // C_t_Car,   /* tv */  !!!
  0x017D, // C_Z_Car,   /* Zv */
  0x017E, // C_z_Car,   /* zv */

  0x0100, // C_A_Macr,  /* A_ */
  0x0101, // C_a_Macr,  /* a_ */
  0x0112, // C_E_Macr,  /* E_ */
  0x0113, // C_e_Macr,  /* e_ */
  0x012A, // C_I_Macr,  /* I_ */
  0x012B, // C_i_Macr,  /* i_ */
  0x014C, // C_O_Macr,  /* O_ */
  0x014D, // C_o_Macr,  /* o_ */
  0x016A, // C_U_Macr,  /* U_ */
  0x016B, // C_u_Macr,  /* u_ */

  0x00C4, // C_A_Diaer, /* A.. */
  0x00E4, // C_a_Diaer, /* a.. */
  0x00CB, // C_E_Diaer, /* E.. */
  0x00EB, // C_e_Diaer, /* e.. */
  0x00CF, // C_I_Diaer, /* I.. */
  0x00EF, // C_i_Diaer, /* i.. */
  0x00D6, // C_O_Diaer, /* O.. */
  0x00F6, // C_o_Diaer, /* o.. */
  0x00DC, // C_U_Diaer, /* U.. */
  0x00FC, // C_u_Diaer, /* u.. */
  0x0178, // C_Y_Diaer, /* Y.. */
  0x00FF, // C_y_Diaer, /* y.. */

  0x0401, // C_E_Cyr_Diaer, /* E.. */
  0x0451, // C_e_Cyr_Diaer, /* e.. */

  0x00C5, // C_A_Ring,  /* Ao */
  0x00E5, // C_a_Ring,  /* ao */
  0x016E, // C_U_Ring,  /* Uo */
  0x016F, // C_u_Ring,  /* uo */

  C_Nul, // 0x0122, // C_G_Tacom, /* G' */  !!!
  C_Nul, // 0x0123, // C_g_Tacom, /* g' */

  0x0122, // C_G_Bcomma,/* G, */
  0x0123, // C_g_Bcomma,/* g, */  !!!
  0x0136, // C_K_Bcomma,/* K, */
  0x0137, // C_k_Bcomma,/* k, */
  0x013B, // C_L_Bcomma,/* L, */
  0x013C, // C_l_Bcomma,/* l, */
  0x0145, // C_N_Bcomma,/* N, */
  0x0146, // C_n_Bcomma,/* n, */
  0x0156, // C_R_Bcomma,/* R, */
  0x0157, // C_r_Bcomma,/* r, */

  0x00C7, // C_C_Cedil, /* C, */
  0x00E7, // C_c_Cedil, /* c, */
  0x015E, // C_S_Cedil, /* S, */
  0x015F, // C_s_Cedil, /* s, */
  C_Nul, // C_T_Cedil, /* T, */
  C_Nul, // C_t_Cedil, /* t, */

  0x00C0, // C_A_Grave, /* A` */
  0x00E0, // C_a_Grave, /* a` */
  0x00C8, // C_E_Grave, /* E` */
  0x00E8, // C_e_Grave, /* e` */
  0x00CC, // C_I_Grave, /* I` */
  0x00EC, // 0xE00C, // Vytis // C_i_Grave, /* i` */
  0x00D2, // C_O_Grave, /* O` */
  0x00F2, // C_o_Grave, /* o` */
  0x00D9, // C_U_Grave, /* U` */
  0x00F9, // C_u_Grave, /* u` */

  0x00C1, // C_A_Acute, /* A' */
  0x00E1, // C_a_Acute, /* a' */
  0x0106, // C_C_Acute, /* C' */
  0x0107, // C_c_Acute, /* c' */
  0x00C9, // C_E_Acute, /* E' */
  0x00E9, // C_e_Acute, /* e' */
  0x00CD, // C_I_Acute, /* I' */
  0x00ED, // 0xE00D, // Vytis // C_i_Acute /* i' */
  0x0139, // C_L_Acute, /* L' */
  0x013A, // C_l_Acute, /* l' */
  0x0143, // C_N_Acute, /* N' */
  0x0144, // C_n_Acute, /* n' */
  0x00D3, // C_O_Acute, /* O' */
  0x00F3, // C_o_Acute, /* o' */
  0x0154, // C_R_Acute, /* R' */
  0x0155, // C_r_Acute, /* r' */
  0x015A, // C_S_Acute, /* S' */
  0x015B, // C_s_Acute, /* s' */
  0x00DA, // C_U_Acute, /* U' */
  0x00FA, // C_u_Acute, /* u' */
  0x00DD, // C_Y_Acute, /* Y' */
  0x00FD, // C_y_Acute, /* y' */
  0x0179, // C_Z_Acute, /* Z' */
  0x017A, // C_z_Acute, /* z' */

  0x040C, // C_K_Cyr_Acute, /* K Cyr ' */
  0x045C, // C_k_Cyr_Acute, /* k Cyr ' */

  0x0150, // C_O_Dacut, /* O'' */
  0x0151, // C_o_Dacut, /* o'' */
  0x0170, // C_U_Dacut, /* U'' */
  0x0171, // C_u_Dacut, /* u'' */

  0x00C3, // C_A_Tilde, /* A~ */
  0x00E3, // C_a_Tilde, /* a~ */
  0x00D1, // C_N_Tilde, /* N~ */
  0x00F1, // C_n_Tilde, /* n~ */
  0x00D5, // C_O_Tilde, /* O~ */
  0x00F5, // C_o_Tilde, /* o~ */

  0x0141, // C_L_Slash, /* L/ */
  0x0142, // C_l_Slash, /* l/ */
  0x00D8, // C_O_Slash, /* O/ */
  0x00F8, // C_o_Slash, /* o/ */

  0x00C2, // C_A_Circ,  /* A^ */
  0x00E2, // C_a_Circ,  /* a^ */
  0x00CA, // C_E_Circ,  /* E^ */
  0x00EA, // C_e_Circ,  /* e^ */
  0x00CE, // C_I_Circ,  /* I^ */
  0x00EE, // C_i_Circ,  /* i^ */
  0x00D4, // C_O_Circ,  /* O^ */
  0x00F4, // C_o_Circ,  /* o^ */
  0x00DB, // C_U_Circ,  /* U^ */
  0x00FB, // C_u_Circ,  /* u^ */

  0x0110, // C_D_Minus, /* D- Island. */
  0x0111, // C_d_Minus, /* d- */
  0x0126, // C_H_Minus, /* H- */
  0x0127, // C_h_Minus, /* h- */
  0x00DE, // C_P_Minus, /* P- */
  0x00FE, // C_p_Minus, /* p- */

  0x00A0, // C_NBSP,   /* No break space */

  0x00A4, // C_Rouble,  /* rublis, $ Cyr */
  0x00A3, // C_Pound,   /* svaras, L/ */
  0x00A5, // C_Yenna,   /* jena, Y- */
  0x00A2, // C_cent,    /* c/ */

  0x00A7, // C_Para,    /* paragrafas, # engl. */
  0x00B6, // C_Pren,    /* paragraph end sign (pastraipos pabaiga, C_pi - pi) */
  0x00D7, // C_Multipl, /* x */
  0x00F7, // C_Divide,  /* -:- */
  0x00B1, // C_PlMin,   /* -+- */
  0x00B9, // C_1up,     /* 1 virsuj */
  0x00B2, // C_2up,     /* 2 virsuj, kvadratu */
  0x00B3, // C_3up,     /* 3 virsuj, kubu */
  0x00AA, // C_a_up,    /* a virsuj */
  0x00BA, // C_o_up,    /* o virsuj */
  0x00BD, // C_Half,    /* 1/2 */
  0x00BC, // C_Quart,   /* 1/4 */
  0x00BE, // C_34,      /* 3/4 */
  0x00AB, // C_Ldopang, /* << - rusiska kabute */
  0x00BB, // C_Rdopang, /* >> - rusiska kabute */
  0x2039, // C_Lang,    /* < */
  0x203A, // C_Rang,    /* > */
  0x00A6, // C_Dvertl,  /* | Koi-7-0 */
  0x00AC, // C_Rminbr,  /* ^ Koi-7-0 ( neiginys, -| ) */
  0x2310, // C_Lminbr,  /* |- */
  0x00B7, // C_Lpoint,  /* mazas taskas vidury */
  0x2022, // didelis (7 is 775 lenteles), 0x2219 - mazesnis (249 is 775), 0x9679 - dar vienas // C_Bpoint,  /* bullet, didelis taskas vidury */
  0x201E, // C_LBquote, /* ,, (" left bellow, double comma, liet. kaire) */
  0x201C, // C_LAquote, /* '' (" left above, double comma above, angl. desine) */
  0x201D, // C_Rquote,  /* `` (" right, reversed double comma above, liet. desine, angl. kaire) */
  0x201A, // C_LBapost, /* , (' left bellow, comma, liet. kaire) */
  0x2018, // C_LAapost, /* ' (' left above, comma above, angl. desine) */
  0x2019, // C_Rapost,  /* ` (' right, grave, reversed comma above, liet. desine, angl. kaire) */

  0x00BF, // C_Qst_Ov,  /* apverstas ? */
  0x00A1, // C_Ex_Ov,   /* apverstas ! */
  0x2026, // C_Dots,    /* ... daugtaskis */
  0x2030, // C_Prom,    /* %o promiles */
  0x2122, // C_TM,      /* TM, Trade Mark */ !!! no coding for UTF-8
  0x00A9, // C_CO,      /* (C) Copyright */ !!! no coding for UTF-8
  0x00AE, // C_RO,      /* (R) */ !!! no coding for UTF-8

/* Additional greek chars, look SGML DTD */
  C_Nul, // 0x03B5, // C_epsilon_var, // straight epsilon  !!!
  C_Nul, // 0x03B8, // C_theta_var,  // curly theta  !!!
  C_Nul, // C_DiGamma,
  C_Nul, // C_digamma,
  C_Nul, // 0x03BA, // C_kappa_var,  // curly kappa  !!!
  C_Nul, // C_DiLambda,
  C_Nul, // C_dilambda,
  C_Nul, // 0x03C0, // C_pi_var,     // curly pi, like C_omega  !!!
  C_Nul, // 0x03C1, // C_rho_var,    // curly rho  !!!
  C_Nul, // C_S, // C_Sigma_var,  // like "S"  !!!
  0x03C2, // C_sigma_var,  // final sigma, like "s"
  C_Nul, // 0x03C6, // C_phi_var,    // curly phi

         /* additional accents, all of them have no width (over the next letter) */
  0x0300, // C_GraveAcc,    /* `  Grave Accent (C_Grave, kairysis kirtis), over the next letter */
  0x02C6, // C_CircAcc,     /* ^  Circumflex Accent (C_Circ), over the next letter */
  0x0303, // C_TildeAcc,    /* ~  Tilde (C_Tilde), over the next letter */
  0x02D8, // C_BreveAcc,    /* u  (lankelis virsuje) */
  C_Nul, // C_SlashAcc,    /* /  Slash, Solidus (Istrizas bruksnys per raide) */
  0x0323, // C_BdotAcc,     /* .  Dot bellow */
  C_Nul, // C_UnderlAcc,   /* _  Underline (Pabraukimas) */

  0x2032, // 0xF0A2, // C_prim,    /* strichas prie raides (C_Acute, C_Apost) */  !!!
  0x2033, // 0xF0B2, // C_dprim,   /* du strichai (C_Dacut) */  !!!

  C_Nul, // C_Each,    /* V - "kiekvienam" - apversta A raide */
  C_Nul, // C_Exists,  /* E - "egzistuoja" - apversta E raide */

  0xF0C0, // C_Aleph,   /* N - alefas */
  0xF0C1, // C_Im,      /* C_I_Got */
  0xF0C2, // C_Re,      /* C_R_Got */
  0xF0C3, // C_wp,      /* C_p_Got */

  0x2264, // 0xF0A3, // C_le,      /* <= - maziau arba lygu */  !!!
  0x2265, // 0xF0B3, // C_ge,      /* >= - daugiau arba lygu */  !!!
  0x2260, // 0xF0B9, // C_ne,      /* =/= - nelygu */  !!!
  C_Nul, // C_ll,      /* << */
  C_Nul, // C_gg,      /* >> */
  C_Nul, // C_Tilde, // C_sim,     /* ~ - panasu */  !!!
  C_Nul, // C_simeq,   /* ~- - panasu arba sutampa */
  0x2248, // 0xF0BB, // C_approx,  /* ~~ - apytiksliai lygu */  !!!
  C_Nul, // C_cong,    /* ~= - kongruentu */
  0x2261, // 0xF0BA, // C_equiv,   /* = - triguba lygybe - ekvivalentu */  !!!

  0x221A, // 0xF0D6, // C_sqrt,    /* square root */  !!!
  0x222B, // 0xF0F2, // C_int,     /* integralas */  !!!
  C_Nul, // C_oint,    /* kreivinis integralas */
  0x2211, // 0xF0E5, // C_Sum,     /* sum sign (C_Sigma) */  !!!
  0x220F, // 0xF0D5, // C_Prod,    /* C_Pi */  !!!
  0xF0C4, // C_O_times, /* OX - O perbraukta kryzmai */
  0xF0C5, // C_O_plus,  /* O+ - O perbraukta pliusu */

  0x221E, // 0xF0A5, // C_infty,   /* infinity - begalybe */  !!!
  0xF0B5, // C_propto,  /* (C_alpha) */
  0x2202, // 0xF0B6, // C_part,    /* partial (C_delta) */  !!!
  0x2205, // 0xF0C6, // C_empty,   /* O/ (C_O_Slash) */

  0x2206, // C_triangle,/* C_Delta - trikampis */

  0xF0D1, // C_nabla,   /* V - C_Delta apversta */

  0xF05E, // C_perp,    /* T apversta - statmena */
  0xF0D0, // C_angle,   /* < - kampas (geom.) */

  0xF0E1, // C_langle,  /* < - skliaustas !!! keisti i C_Lang */
  0xF0F1, // C_rangle,  /* > - skliaustas !!! keisti i C_Rang */
  

  0xF0C8, // 0x2229 ???!!! // C_cap,     /* U apversta - pjuvis */
  0xF0C7, // C_cup,     /* U - junginys */

  C_Nul, // C_V, // C_vee,     /* V */  !!!
  C_Nul, // 0x039B, // C_wedge,   /* C_Lambda */  !!!

  0xF0C9, // C_supset,  /* D - virsaibis */
  0xF0CA, // C_supseteq,/* D= - virsaibis arba sutampa */
  0xF0CC, // C_subset,  /* C - poaibis */
  0xF0CD, // C_subseteq,/* C= - poaibis arba sutampa */
  0xF0CB, // C_nsubset, /* C/ - nepoaibis */

  0xF0CE, // C_in,      /* C_epsilon_var - priklauso */
  0xF0CF, // C_notin,   /* C_epsilon_var_Slash - nepriklauso */
  0xF027, // C_ni,      /* C_epsilon_var apsuktas - apima */

  0x2190, // 0xF0AC, // C_leftarr,       /* <-- */  !!!
  0x2192, // 0xF0AE, // C_rightarr,      /* --> */  !!!
  0x2194, // 0xF0AB, // C_leftrightarr,  /* <--> */  !!!
  0x2191, // 0xF0AD, // C_uparr,         /* ^| */  !!!
  0x2193, // 0xF0AF, // C_downarr,       /* |v */  !!!
  0x2195, // C_updownarr,     /* ^|v */

  0xF0DC, // C_Leftarr,       /* <== */
  0xF0DE, // C_Rightarr,      /* ==> */
  0xF0DB, // C_Leftrightarr,  /* <==> */

  0xF0DD, // C_Uparr,         /* ^|| */
  0xF0DF, // C_Downarr,       /* ||v */
  C_Nul, // C_Updownarr,     /* ^||v */

  C_Nul, // C_mid,           /* | */
  C_Nul, // C_paral,         /* || */

  0x25CA, // C_diamond,     /* rombas */

  0x2663, // C_Club,        /* giles */
  0x2666, // C_Diamond,     /* bugnai */
  0x2665, // C_Heart,       /* cirvai sirdys */
  0x2660, // C_Spade,       /* pikai lapai */


  0x00AD, // C_hyph,    /* hidden hyphenation sign ("\-" for TEX) */
  C_Nul, // C_break,   /* line break character */

  0x01CE, // C_a_Car,   /* av - laikinai, po to ismesti !!! */

  0x20AC, // C_euro,    /* C= euro piniginis vienetas !!! kelti prie pinigu */

  0x00B0, // C_deg,     /* degree - panasiai, kaip C_Ring, tik desineje */
  0x00B5, // C_micro,   /* mikro - panasiai, kaip C_my */
  0x2126, // C_Ohm,     /* Ohm sign - panasiai, kaip C_Omega */
  C_Nul, // 0x00C5, // C_Angst,   /* Angstroem - C_A_Ring */  !!!

  0x2500, // C_Horl,    /* horizontal line --- */

  0x2020, // C_Dag,    /* Dagger +| (kryzius) */
  0x2021, // C_Ddag,   /* Double dagger +|+ (Kestucio kryzius) */

  C_Nul, // C_ff,     /* ff ligature */
  C_Nul, // C_fi,     /* fi ligature */
  C_Nul, // C_fj,     /* fj ligature */
  C_Nul, // C_ffi,    /* ff ligature */
  C_Nul, // C_ffl,    /* ff ligature */
  C_Nul, // C_fl,     /* ff ligature */

  0x2227, // 0xF0D9, // C_and,    /* ^ logical and, konjunkcija */
  0x2228, // 0xF0DA, // C_or,     /* V logical or, disjunkcija */

  0xF0A6, // 0x0192 ???!!! // C_fun,    /* f function of */

  C_Nul, // C_MinPl,  /* -+ minus plus */

  0x2013, // C_EnDash, /* -- - vidutinio ilgio bruksnys */
  0x2014, // C_EmDash, /* --- - ilgas bruksnys */


  C_Nul, // C_Cdots,  /* ... - daugtaskis per viduri */
  C_Nul, // C_WideTilde, /* ~ didele tilde */

  0x2005, // C_QemSpc, /* 1/4 m space */
  0x2002, // C_EnSpc,  /* n space */
  0x2003, // C_EmSpc,  /* m space */
  C_Nul, // C_2emSpc, /* 2 m space */


  C_Nul, // C_NewPar, /* paragraph end control character */

// lithuanian accented letters
  0x1EF2, // C_Y_Grave,   // Y`
  0x1EF3, // C_y_Grave,   // y`
  0x1EBC, // C_E_Tilde,   // E~
  0x1EBD, // C_e_Tilde,   // e~
  0x0128, // C_I_Tilde,   // I~
  0x0129, // 0xE00E, // Vytis // C_i_Tilde,   // i~
  0x0168, // C_U_Tilde,   // U~
  0x0169, // C_u_Tilde,   // u~
  0x1EF8, // C_Y_Tilde,   // Y~
  0x1EF9, // C_y_Tilde,   // y~
  C_Nul, // 0xE015, // Vytis // C_L_Tilde,   // L~
  C_Nul, // 0xE016, // Vytis // C_l_Tilde,   // l~
  C_Nul, // 0xE017, // Vytis // C_M_Tilde,   // M~
  C_Nul, // 0xE018, // Vytis // C_m_Tilde,   // m~
  C_Nul, // 0xE019, // Vytis // C_R_Tilde,   // R~
  C_Nul, // 0xE01A, // Vytis // C_r_Tilde,   // r~
  C_Nul, // 0xE000, // Vytis // C_A_Ogon_Acute,
  C_Nul, // 0xE001, // Vytis // C_a_Ogon_Acute,
  C_Nul, // 0xE004, // Vytis // C_E_Ogon_Acute,
  C_Nul, // 0xE005, // Vytis // C_e_Ogon_Acute,
  C_Nul, // 0xE008, // Vytis // C_E_Adot_Acute,
  C_Nul, // 0xE009, // Vytis // C_e_Adot_Acute,
  C_Nul, // 0xE00F, // Vytis // C_I_Ogon_Acute,
  C_Nul, // 0xE010, // Vytis // C_i_Ogon_Acute,
  C_Nul, // 0xE01B, // Vytis // C_U_Ogon_Acute,
  C_Nul, // 0xE01C, // Vytis // C_u_Ogon_Acute,
  C_Nul, // 0xE01F, // Vytis // C_U_Macr_Acute,
  C_Nul, // 0xE020, // Vytis // C_u_Macr_Acute,
  C_Nul, // C_A_Ogon_Grave,
  C_Nul, // C_a_Ogon_Grave,
  C_Nul, // C_E_Ogon_Grave,
  C_Nul, // C_e_Ogon_Grave,
  C_Nul, // C_E_Adot_Grave,
  C_Nul, // C_e_Adot_Grave,
  C_Nul, // C_I_Ogon_Grave,
  C_Nul, // C_i_Ogon_Grave,
  C_Nul, // C_U_Ogon_Grave,
  C_Nul, // C_u_Ogon_Grave,
  C_Nul, // C_U_Macr_Grave,
  C_Nul, // C_u_Macr_Grave,
  C_Nul, // 0xE002, // Vytis // C_A_Ogon_Tilde,
  C_Nul, // 0xE003, // Vytis // C_a_Ogon_Tilde,
  C_Nul, // 0xE006, // Vytis // C_E_Ogon_Tilde,
  C_Nul, // 0xE007, // Vytis // C_e_Ogon_Tilde,
  C_Nul, // 0xE00A, // Vytis // C_E_Adot_Tilde,
  C_Nul, // 0xE00B, // Vytis // C_e_Adot_Tilde,
  C_Nul, // 0xE011, // Vytis // C_I_Ogon_Tilde,
  C_Nul, // 0xE012, // Vytis // C_i_Ogon_Tilde,
  C_Nul, // 0xE01D, // Vytis // C_U_Ogon_Tilde,
  C_Nul, // 0xE01E, // Vytis // C_u_Ogon_Tilde,
  C_Nul, // 0xE021, // Vytis // C_U_Macr_Tilde,
  C_Nul, // 0xE022, // Vytis // C_u_Macr_Tilde,

// phonetic characters; vowels:
  0x0251,  // C_ph_a,        // low back unrounded; a, open a; italic C_a
  0x0252,  // C_ph_a_inv,    // low back rounded; oa; inverted italic C_a

  0x028C,  // C_ph_a_sh,     // low-mid back unrounded; short a; inverted C_v
  0x0254,  // C_ph_o_sh,     // low-mid back rounded; short o, open o; inverted C_c
// o,                // C_ph_o,        // mid back rounded?; o, closed o; C_o

  0x028A,  // 0x028B, // Vytis // 0x028A,  // C_ph_u_sh,     // semi-high back rounded; short u, short open u; C_ypsilon
  0x0277,  // C_ph_w_sh,     // semi-high back rounded; short u, short open u, obsolete; C_omega
// u,                // C_ph_u,        // semi-high central rounded?; u, closed u; C_u
// y,                // C_ph_u_soft,   // high central rounded; soft u, iu, german C_u_Diaer; C_y,

  0x025B,  // C_ph_e_sh,     // low-mid front unrounded; short e, open e; C_epsilon 
  C_Nul,             // C_ph_ae,       // low front unrounded?; e, open e; C_ae, 0x00E6
// e,                // C_ph_e_cl,     // high central unrounded?; closed e, german e; C_e
  0x025C,  // C_ph_e_sh_inv, // low-mid central unrounded; hard e; inverted C_epsilon
  0x0259,  // C_ph_e_inv,    // mid central unrounded; reduced e; inverted C_e

  0x026A,  // C_ph_i_sh,     // semi-high front unrounded; short i, short open i; C_i without dot
// i,                // C_ph_i,        // high front unrounded?; i, closed i; C_i

// phonetic characters; consonants:
  0x0283,  // C_ph_sh,       // sh; C_f, C_int 
  0x0293,  // 0x0292,  // Vytis // 0x0293,  // C_ph_zh,       // zh; C_3
  0x02A7,  // C_ph_tsh,      // tsh; C_t C_f, C_t C_int
  0x02A4,  // C_ph_dzh,      // dzh; C_d C_3
  0x0275,  // C_ph_th_b,     // breath th; C_theta
  C_Nul,             // C_ph_th_v,     // voiced th; C_delt_Mn, (C_delta_Minus, 0x00F0)
  0x0273,  // C_ph_ng,       // nasal g; C_eta
  0x0261,  // C_ph_g,        // g; italic C_g  
  
// additional phonetic characters:
  C_Nul, // C_ph_oe,       // high back rounded?; soft o, open soft o, io, german C_o_Diaer; C_oe, 0x0153
  C_Nul, // C_ph_o_slash,  // high back rounded?; soft o, closed soft o, io, german C_o_Diaer; C_o_Slash, 0x00F8

  C_Nul, // C_ph_a_l,      // low back unrounded long; a long, open a long; a:, italic C_a C_Colon
  C_Nul, // C_ph_e_inv_l,  // mid central unrounded long; reduced e long; e:, inverted C_e C_Colon
  C_Nul, // C_ph_i_l,      // high front unrounded long?; i long, closed i long; i:, C_i C_Colon
  C_Nul, // C_ph_o_l,      // low-mid back rounded long; o long, open o long; o:, inverted C_c C_Colon
  C_Nul, // C_ph_u_l,      // ; u long; C_u C_Colon

  C_Nul, // C_ph_a_n,      // low back unrounded nasal; a nasal, open a nasal; a~, italic C_a C_TildeAcc
  C_Nul, // C_ph_a_str_n,  // a nasal; a~, C_a_Tilde, 0x00E3
  C_Nul, // C_ph_e_n,      // low-mid front unrounded nasal; short e nasal, open e nasal; e~, C_epsilon C_TildeAcc
  C_Nul, // C_ph_oe_n,     // oe nasal; oe~, C_oe C_TildeAcc
  C_Nul, //                // C_ph_o_n,   // low-mid back rounded nasal; open o nasal; o~, inverted C_c + C_TildeAcc

  C_Nul, // 0x00E7,  // C_ph_ch,       // german ch; C_c_Cedil

// diphtongs
  C_Nul, // C_ph_ai_d,  //  C_a C_LigaLow C_i
  C_Nul, // C_ph_ae_d,  //  C_a C_LigaLow C_e
  C_Nul, // C_ph_ao_d,  //  C_a C_LigaLow C_o
  C_Nul, // C_ph_au_d,  //  C_a C_LigaLow C_u
  C_Nul, // C_ph_ei_d,  //  C_e C_LigaLow C_i
  C_Nul, // C_ph_eu_d,  //  C_e C_LigaLow C_u
  C_Nul, // C_ph_ie_d,  //  C_i C_LigaLow C_e
  C_Nul, // C_ph_oe_d,  //  C_ph_o_sh C_LigaLow C_ph_o_slash
  C_Nul, // C_ph_oy_d,  //  C_ph_o_sh C_LigaLow C_y
  C_Nul, // C_ph_uo_d,  //  C_u C_LigaLow C_o

// breved phonetics
  C_Nul, // 0x012D   // C_ph_i_Brev,   // ; j; C_i_Brev
  C_Nul, // C_ph_o_Brev,  //  C_o_Brev
  C_Nul, // C_ph_u_Brev,  //  C_u_Brev

// liga accents (for diphtongs)
  C_Nul, // C_LigaUp,      // lankelis virs dvieju raidziu
  C_Nul, // C_LigaLow,     // lankelis po dviem raidem

  0x25E6,     // 0x9675 - dar vienas // C_MidRing,     // mazas apskritimas viduryje (tusciaviduris bulletas - kaip C_Bpoint)

// phonetic accents
   C_Nul, // C_ph_acc,       // C_Apost
   C_Nul, // C_ph_acc_low,   // C_Comma

   0x9633, // 0x25A1, // C_square,      // tusciaviduris kvadratas viduryje

   0x2642, // C_male,        // vyr. lytis, male sex, mars, o^
   0x2640, // C_female,      // mot. lytis, female sex, venus, o+

   C_Nul, // C_O_ring,      // Oo - mazas apskritimas O viduje
   C_Nul, // C_O_dot,       // O. - taskas O viduje

   0x25CB, // C_BigRing,     // didelis apskritimas, C_O

   C_Nul, // C_longleftarr,       /* <---- */
   C_Nul, // C_longrightarr,      /* ----> */

   C_Nul, // C_smile,       // lankas, ~C_LigaLow

   0x9632, // 0x25A0, // 0x9632 didesnis, 0x9642 mazesnis, C_box,         // pilnaviduris kvadratas viduryje

// DOS frames
   0x2502, //    C_v_b,       // vert; ne DOS-e - C_Vertl
   0x2500, //    C_h_b,       // hor; ne DOS-e - C_Horl
   0x253C, //    C_vh_b,      // vert hor
   0x2524, //    C_vl_b,      // vert left
   0x251C, //    C_vr_b,      // vert right
   0x2534, //    C_hu_b,      // hor up
   0x252C, //    C_hd_b,      // hor down
   0x2518, //    C_ul_b,      // up left
   0x2510, //    C_dl_b,      // down left
   0x2514, //    C_ur_b,      // up right
   0x250C, //    C_dr_b,      // down right

   0x2551, //    C_2v_b,      // double vert; C_paral
   0x2550, //    C_2h_b,      // double hor
   0x256C, //    C_2v2h_b,    // double vert double hor
   0x2563, //    C_2v2l_b,    // double vert double left
   0x2560, //    C_2v2r_b,    // double vert double right
   0x2569, //    C_2h2u_b,    // double hor double up
   0x2566, //    C_2h2d_b,    // double hor double down
   0x255D, //    C_2u2l_b,    // double up double left
   0x2557, //    C_2d2l_b,    // double down double left
   0x255A, //    C_2u2r_b,    // double up double right
   0x2554, //    C_2d2r_b,    // double down double right

   0x256B, //    C_2vh_b,     // double vert hor
   0x2562, //    C_2vl_b,     // double vert left
   0x255F, //    C_2vr_b,     // double vert right
   0x2568, //    C_h2u_b,     // hor double up
   0x2565, //    C_h2d_b,     // hor double down
   0x255C, //    C_2ul_b,     // double up left
   0x2556, //    C_2dl_b,     // double down left
   0x2559, //    C_2ur_b,     // double up right
   0x2553, //    C_2dr_b,     // double down right
   
   0x256A, //    C_v2h_b,     // vert double hor
   0x2561, //    C_v2l_b,     // vert double left
   0x255E, //    C_v2r_b,     // vert double right
   0x2567, //    C_2hu_b,     // double hor up
   0x2564, //    C_2hd_b,     // double hor down
   0x255B, //    C_u2l_b,     // up double left
   0x2555, //    C_d2l_b,     // down double left
   0x2558, //    C_u2r_b,     // up double right
   0x2552, //    C_d2r_b,     // down double right
   
   0x2588, //    C_block,     // pilnaviduris kvadratas per visa laukeli
   0x2593, //    C_dgrblk,    // tamsiai pilkas ---//--- (75% shaded)
   0x2592, //    C_grblk,     // pilkas ---//--- (50% shaded)
   0x2591, //    C_lgrblk,    // sviesiai pilkas ---//--- (25% shaded)
   0x2580, //    C_uphblk,    // pilnaviduris staciakampis per puse laukelio virsuje
   0x2584, //    C_dnhblk,    // ---//--- apacioje
   0x258C, //    C_lthblk,    // ---//--- kaireje
   0x2590, //    C_rthblk,    // ---//--- desineje

   0x25B2, // C_utrif, // pilnaviduris lygiakrastis trikampis smaigaliu i virsu, MS Word UTF16
   0x25BC, // C_dtrif, // pilnaviduris trikampis zemyn, MS Word UTF16
   0x25C0, // C_ltrif, // pilnaviduris trikampis i kaire, kodas atsirado, atrodo su projektu HOP, hopt2x.exe; MS Word UTF16, IExplorer ir Netscape C_ltri
   0x25B6, // C_rtrif, // pilnaviduris trikampis i desine, kodas atsirado, atrodo su projektu HOP, hopt2x.exe; MS Word UTF16, IExplorer ir Netscape C_rtri

   C_Nul,  // 0x28A,  // Vytis //    C_ph_uu_sh,       // phonetics: semi-high back rounded; short u, short open u; inverted C_Omega

   C_Nul,  //    C_hhyph,          /* hard hyphen - zodzio kelimas per prievarta "-\hfill\break" */
   C_Nul,  //    C_sbreak,         // soft break \lastwordinpar{5}{...} iki pastraipos (lizdo) pabaigos
   C_Nul,  //    C_hSpc,           // hard space - technical space after TEX commands - do not process
   C_Nul,  //    C_hbreak,         // break su \hfill, xmlsty keiciamas is C_Cr ("\r")
   C_Nul,  //    C_lSpc,           // last space - space, to be changed to C_NBSP after LAST_WORD_LEN
   C_Nul,  //    C_hlSpc,          // hard last space - C_hSpc, to be changed to C_NBSP after LAST_WORD_LEN

   9650,   // C_utrif_rtf, // pilnaviduris lygiakrastis trikampis smaigaliu i virsu, MS Word RTF
   9660,   // C_dtrif_rtf, // pilnaviduris trikampis zemyn, MS Word RTF
   9668,   // C_ltrif_rtf, // pilnaviduris trikampis i kaire, MS Word RTF
   9658,   // C_rtrif_rtf, // pilnaviduris trikampis i desine, MS Word RTF

// erdvines rodykles
   C_Nul,  // C_3DTopLightLeftArrowHead
   C_Nul,  // C_3DBotLightLeftArrowHead
   C_Nul,  // C_3DTopLightRightArrowHead
   C_Nul,  // C_3DBotLightRightArrowHead
   C_Nul,  // C_3DLeftLightUpArrowHead
   C_Nul,  // C_3DRightLightUpArrowHead
   C_Nul,  // C_3DLeftLightDownArrowHead
   C_Nul,  // C_3DRightLightDownArrowHead

   0x2212, // C_MinusMath

   0x200B, // C_ZeroWidthSpace

   0x0294, // C_ph_glot_stop

   0x00B4, // C_AcuteNcomb // nekombinacinis desininis kirtis (C_Acute, C_Apost)
   0x00B8, // C_CedilNcomb // nekombinacine cedilla (C_Cedil)
   0x00AF, // C_MacrNcomb  // nekombinacinis bruksnys virsuje (C_Macr)

   C_Nul,   // C_DollNctrl,    /* $  Currency Sign (Pinigu zenklas) */

   0x02DB, // C_OgonNcomb

   0x2116, // C_No

   0x02C7, // C_CarNcomb
   0x00A8, // C_DiaerNcomb
   C_Nul,   // C_TildeNcomb

   C_Nul,   // C_utri, // tusciaviduris lygiakrastis trikampis smaigaliu i virsu
   C_Nul,   // C_dtri, // tusciaviduris trikampis zemyn
   0x25C4, // C_ltri, // tusciaviduris trikampis i kaire; MS Word UTF16, IExplorer ir Netscape pilnaviduris
   0x25BA, // C_rtri, // tusciaviduris trikampis i desine; MS Word UTF16, IExplorer ir Netscape pilnaviduris

   0x203E, // (8254) // C_Oline
   
   C_Nul,   // C_R_Oline
   C_Nul,   // C_X_Oline

   C_Nul,   // C_leqslant
   C_Nul,   // C_geqslant

   0x00EC, // C_i_Grave_Dotless // C_i_Grave, // i`
   0x00ED, // C_i_Acute_Dotless // C_i_Acute, // i'
   0x0129, // C_i_Tilde_Dotless // C_i_Tilde, // i~


//------------------------- accented cyrillic
   C_Nul,   // C_A_Cyr_Acute
   C_Nul,   // C_E_Cyr_Acute
   C_Nul,   // C_I_Cyr_Acute
   C_Nul,   // C_O_Cyr_Acute
   C_Nul,   // C_U_Cyr_Acute
   C_Nul,   // C_Y_Cyr_Acute
   C_Nul,   // C_Ee_Cyr_Acute
   C_Nul,   // C_Ju_Cyr_Acute
   C_Nul,   // C_Ja_Cyr_Acute
                     
   C_Nul,   // C_a_Cyr_Acute
   C_Nul,   // C_e_Cyr_Acute
   C_Nul,   // C_i_Cyr_Acute
   C_Nul,   // C_o_Cyr_Acute
   C_Nul,   // C_u_Cyr_Acute
   C_Nul,   // C_y_Cyr_Acute
   C_Nul,   // C_ee_Cyr_Acute
   C_Nul,   // C_ju_Cyr_Acute
   C_Nul,   // C_ja_Cyr_Acute

   C_Nul,   // C_NullSpc
};

